### ISSUE TITLE
React Native Build Error

### ISSUE THREAD

**Issue by IronHeartDan** [bitcoinerlab/secp256k1#2]
\node_modules\cipher-base\index.js: stream could not be found within the project or in these directories:

I am using expo.
"react-native": "0.71.7",
"bitcoinjs-lib": "^6.1.0",
"@bitcoinerlab/secp256k1": "^1.0.2",

**Comment by landabaso** [comment]
It appears the `stream` package is not being used directly in `@bitcoinerlab/secp256k1`, but it may be a dependency required by one of the other packages. If I'm not mistaken, this error only surfaced after you installed `@bitcoinerlab/secp256k1`, correct?

Unfortunately, there isn't much I can do to fix this issue directly. However, I recommend installing the `stream` package to resolve the problem. You can do this using the following npm command:

```bash
npm install stream
```
Please try this and let me know if you encounter any further issues.

**Comment by landabaso** [comment]
I'm closing this for now. Let me know if you need further assistance.
