### ISSUE TITLE
Would it be possible to update the noble libraries

### ISSUE THREAD

**Issue by tian000** [bitcoinerlab/secp256k1#6]

**Comment by landabaso** [comment]
For `@noble/secp256k1`, version 1.7.1 is currently the latest in the v1 series. Before considering any updates, I'll need to review any changes and their potential impact on the project. As of now, I don’t have immediate plans to upgrade it.

Regarding `@noble/hashes`, an update might be more straightforward. I'll look into it.

Could you please elaborate more on which specific versions you're interested in and describe the use case or reason for the upgrade request? This will help me understand your needs better.

**Comment by paulmillr** [comment]
@landabaso v1 is not supported anymore. Its security is also weaker than noble-curves.

You should either upgrade to v2 (which doesn't have Schnorr), or to noble-curves (which was audited like 3 times and has everything).

**Comment by landabaso** [comment]
Thanks for pointing this out, @paulmillr I'll look into it.

**Comment by landabaso** [comment]
I have migrated the codebase to use @noble/curves in [Pull Request #10](https://github.com/bitcoinerlab/secp256k1/pull/10). I'll leave it open until the end of the week in case you'd like to take a quick look, @paulmillr.

**Comment by landabaso** [comment]
Closed in #10
